use_frameworks!

platform :ios, '10.0'

target 'UKAppDelegateMoudle_Example' do
  pod 'UKAppDelegateMoudle', :path => '../'

  target 'UKAppDelegateMoudle_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
