use_frameworks!

platform :ios, '10.0'

target 'UKAppDelegateMoudle_Example' do
  pod 'UKAppDelegateMoudle', :path => '../'

  target 'UKAppDelegateMoudle_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "11.0"
    end
  end
end
